### ISSUE TITLE
一个200*200的div在不同分辨率屏幕上下左右居中，用css实现

### ISSUE THREAD

**Issue by Sogrey** [Sogrey/Web-QA#70]
``` css
div
  {
  position:absolute;
  width:200px;
  height:200px;
  top:50%;
  left:50%;
  margin-left:-100px;
  height:-100px;
  z-index:1000;
  }
```
