### ISSUE TITLE
写一个左中右布局占满屏幕，其中左右两块是固定宽度200 ，中间自适应宽，要求先加载中间块，请写出结构及样式：

### ISSUE THREAD

**Issue by Sogrey** [Sogrey/Web-QA#71]
``` html
<body>  

        <h3>实现三列宽度自适应布局</h3>  
       
        <div id = "left">我是左边</div>  
       
        <div id = "right">我是右边</div>  
       
        <div id = "center">我是中间</div>  

</body>  
```

``` css
html,body{ margin: 0px;width: 100%; }  

h3{height: 100px;margin:20px 0 0;}  

#left,#right{width: 200px;height: 200px; background-color: #ffe6b8;position: absolute;top:120px;}  

#left{left:0px;}  

#right{right: 0px;}  

#center{margin:2px 210px ;background-color: #eee;height: 200px; }  
```
